# Generated by Django 3.2 on 2021-05-07 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boxer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('nick_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blue_corner', models.IntegerField()),
                ('title_fight', models.BooleanField()),
                ('scheduled_rounds', models.IntegerField()),
                ('decision_round', models.IntegerField()),
                ('decision_type', models.IntegerField()),
                ('winner', models.IntegerField()),
                ('red_corner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.boxer')),
            ],
        ),
        migrations.AddField(
            model_name='boxer',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.style'),
        ),
    ]
