# Generated by Django 3.2 on 2021-05-07 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boxer',
            new_name='Boxers',
        ),
        migrations.RenameModel(
            old_name='Style',
            new_name='Styles',
        ),
    ]
