# Generated by Django 3.2 on 2021-05-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_auto_20210507_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fight',
            old_name='blue_corner',
            new_name='blue_corner_id',
        ),
        migrations.RenameField(
            model_name='fight',
            old_name='red_corner',
            new_name='red_corner_id',
        ),
        migrations.RenameField(
            model_name='fight',
            old_name='winner',
            new_name='winner_id',
        ),
    ]
